import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/utils/providers/QueryProvider";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/sonner";
import '@mantine/charts/styles.css';
import '@mantine/core/styles.css';
import { MantineProvider } from '@mantine/core';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jiku Finance",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative `}>
      <SessionProvider>
        <QueryProvider>
          <MantineProvider>
          {children}
          </MantineProvider>
          <Toaster className="bg-white text-black " />
        </QueryProvider>
      </SessionProvider>
      </body>
    </html>
  );
}
